services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # Change this password
      POSTGRES_DB: raweditor
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  editor:
    image: ghcr.io/poesterlin/raw-editor:main
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/raweditor # Update 'password' if you changed it above
      - CLUT_DIR=/app/cluts
      - IMPORT_DIR=/app/import
      - EXPORT_DIR=/app/export
      - TMP_DIR=/tmp
    volumes:
      - ./cluts:/app/cluts        # for custom CLUTs, if needed
      - ./import:/app/import      # import directory 
      - ./export:/app/export      # export directory  
      - ./data:/app/data          # optional, persist google photos tokens
    ports:
      - "4893:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
